### ISSUE TITLE
Switching board causes network not to work anymore

### ISSUE THREAD

**Issue by ffes** [debian-pi/raspbian-ua-netinst#103] opened 2014-09-04 09:46 UTC
Yesterday I installed a new image on a pi. Network works as expected.

After that I put the sd-card in another pi and eth0 was not working anymore, so no network access was possible.

Searching in the forums resulted in two post that describe (and fix) this problem:

http://www.raspberrypi.org/forums/viewtopic.php?f=28&t=82467
http://www.raspberrypi.org/forums/viewtopic.php?f=6&t=5442

It turns out that the /etc/udev/rules.d/70-persistent-net.rules added a new rules where eth1 is linked to the mac of the second pi and therefore a mismatch with /etc/network/interfaces

Moving the rules-file out of the way causes that file to be recreated again on reboot with the proper mac address.

In my original installation (based on an official foundation image from the early days) this file is not created at all. Switching boards always worked. I haven't tried a recent image.

With this behavior (adding eth1 to the new mac) switching a sd card between different pi's is sort of impossible.

**Comment by diederikdehaas** [comment] 2015-02-09 18:53
On the image from the Raspberry Pi Foundation (Raspbian d.d. 2015-01-31) they removed `eth0` and `wlan*[0-9]` from `/lib/udev/rules.d/75-persistent-net-generator.rules` to tackle this issue.

**Comment by cherylquirion** [comment] 2016-02-04 20:43
We are putting the same image on a large number of Raspberry Pis. Therefore we had to ensure that the /etc/udev/rules.d/70-persistent-net.rules is recreated every time a device boots up. We also move memory cards from one device to another for testing and in the field. Therefore, in the /rootfs/lib/udev/write_net_rules script, we added a line to delete /etc/udev/rules.d/70-persistent-net.rules  so that it is recreated every time.

**Comment by Mausy5043** [comment] 2016-02-05 16:08
Good idea. I assume you're using `sed` in `post-install.txt` to modify the file?

**Comment by cherylquirion** [comment] 2016-02-05 16:34
We can't do it as part of the `post-install.txt ` because we swap memory cards between devices in the field if/when required - no copying involved... same memory card in a different device. The `70-persistent-net.rules` file has to be deleted at boot. So we had to change the  `write_net_rules` script by adding a line to delete the `70-persistent-net.rules` file when the script starts. We override the `write_net_rules` script in our build process.

**Comment by kpfleming** [comment] 2016-02-06 20:09
Instead of modifying that script, you can just remove ```/lib/udev/rules.d/75-persistent-net-generator.rules```. Then the ```write_net_rules``` script will never be called.

**Comment by Mausy5043** [comment] 2016-03-05 20:39
Is this still an issue?

**Comment by diederikdehaas** [comment] 2016-03-05 21:02
> Is this still an issue?

Yes. Just put a sd card from one Pi into another and the network didn't come up.
You should look in `/etc/udev/rules.d/70-persistent-net.rules` and there you will find the MAC address(es) :wink:

**Comment by cherylquirion** [comment] 2016-03-05 21:19
It is still a problem. I tested with the latest version and published a workaround that we needed to implement.

**Comment by Mausy5043** [comment] 2016-03-05 21:29
And the issue is with the *installed system* being moved to another Pi, right? Or are you trying to run the *installer* (again) on a different board?
Sorry I ask, but its not entirely clear to me.

**Comment by cherylquirion** [comment] 2016-03-05 21:34
This is on an installed system. We create a release image that is then used on hundred(s) of different Raspberry devices installed in different vehicles.

**Comment by Mausy5043** [comment] 2016-03-05 21:34
:OK: thanks

**Comment by Mausy5043** [comment] 2016-03-05 21:42
Oh wait 
    `/etc/udev/rules.d/70-persistent-net.rules` 
NOT `/lib/udev/rules.d/75-persistent-net-generator.rules`
I've been staring at the wrong file all this time :grin:

**Comment by diederikdehaas** [comment] 2016-03-05 22:04
> I've been staring at the wrong file all this time

Maybe it's time to call it a day? :stuck_out_tongue_winking_eye:

**Comment by goranche** [comment] 2016-03-06 06:38
@Mausy5043 it's a (as so many things these days are) a *systemd* issue (well, udev, really; same difference)... it's called [Predictable Network Interface Names](https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/) and it should be easy to find additional info on this... (just google [predictable network interface names](http://lmgtfy.com/?q=predictable+network+interface+names) :innocent: )
there is a section on how to disable it in the document... (and in systemd fashion it mentions 4 methods of doing so, but lists 3... nope, I'm not a systemd fan)

but IMHO we should leave disabling this to the end user... document it, yes, of course, but leave the default state as is in the default installer...

**Comment by kpfleming** [comment] 2016-03-08 11:21
I agree, predictable interface naming is very useful. It doesn't matter for the Pi's built-in Ethernet of course, but for USB-attached WiFi interfaces it could be very important, as the interface name could change as a result of moving the interface to a different USB port (when MAC-based naming is not in use).

**Comment by dicer** [comment] 2016-03-08 12:29
Maybe it could just be disabled for ethernet then? It is pretty annoying
and took me quite a while to find back then.

**Comment by goranche** [comment] 2016-03-08 12:43
> predictable interface naming is very useful

you must have been sent from the devil... :grin: 
(but yes... I agree that for many "normal" people it might be useful... I hate it)

**Comment by richard-scott** [comment] 2016-03-09 12:00
Here is a way to fix the problem. Udev records the MAC address of a network interface in this file:

/etc/udev/rules.d/70-persistent-net.rules

You need to blank out the contents of this file with this command:
```
# >/etc/udev/rules.d/70-persistent-net.rules
```
And then make it unwritable by anyone (including root) with this command:
```
# chattr +i /etc/udev/rules.d/70-persistent-net.rules
```
As long as you don't move your network interfaces (i.e. wifi) to different USB slots you should get the same interface name after reboot even after moving SD Card to different hardware.

**Comment by Mausy5043** [comment] 2016-03-20 18:42
PR#391 was merged in an attempt to fix this issue.
Closing the issue. 
Please feel free to re-open if you find the issue is not resolved.

**Closed by Mausy5043** 2016-03-20 18:42 UTC

**Comment by goranche** [comment] 2016-03-20 18:44
@cherylquirion I think you'll find that the latest changes will be better suited to what you're trying to do (I have a "large scale" deployment as well, same image, ...)

also, if you'd like, I could give you part of my `post-install.txt` (and a script or two) that makes the system readonly (optionally having a partition read write), and thus highly improving the reliability of the installed device...

**Comment by cherylquirion** [comment] 2016-03-21 01:18
@goranche would love to see the scripts - thanks! Sounds like we have a similar deployment (we currently hundreds of devices, and by the end of the year - thousands). Look forward to seeing those updates.

**Comment by goranche** [comment] 2016-03-21 06:41
@cherylquirion sure... you can find the main part [here](https://github.com/goranche/raspbian-ua-netinst-ro)...

if you need to add a third partition, that stays read write (this is my case), then I recommend using an installer built from the v1.1.x branch, copying the `scripts/etc/init.d/rcS` (from the repository) file to `config/installer/rcS` on the SD card (this will cause the installer to run this file instead of the original on in the cpio archive), and applying [this patch](https://github.com/goranche/raspbian-ua-netinst/commit/3d9b2a7a13336d8fc8c251cb6f3cbfd9a09898ee)...  (this will probably not become part of the installer, BTW)
this will allow you to add a `post-fdisk.txt` file to the SD card, where you can manipulate the partition table during the install...

(as is, the installer doesn't allow for a hook early enough in the process, that would allow altering the partition table without the need for a reboot of the kernel, to read the new partition table... that's why I added that patch)

you only need to make sure you set bootsize and rootsize in `installer-config.txt` to some values that leave some space on the SD card... the content of `post-fdisk.txt` I'm using (this could be made more robust, but it works for me :blush: ):
```
# Create additional partition
fdisk "${bootdev}" &>/dev/null <<EOF
n
p
3


w
EOF
```

the resulting system will boot with both `/boot` and `/root` read-only, which means that a sudden power loss will not result in a corrupt filesystem, so you can be relatively certain, that it will boot up again...
if needed, one could add a boot-up script that checks if the read-write partition is ok (do a fsck), and if needed, recreate the partition...

that's a quick overview... let me know if you need anything more (my current post-install.txt is around 450 lines long, and includes about 30 additional files... much functionality for headless deploys was added :sunglasses: )

**Comment by goranche** [comment] 2016-03-21 06:58
one fortunate side effect is that persistent naming doesn't work, as udev can't write out the calculated names :smiling_imp:
