### ISSUE TITLE
eth0 not found

### ISSUE THREAD

**Issue by aristosv** [debian-pi/raspbian-ua-netinst#302] opened 2015-10-28 05:16 UTC
The netinst works just fine on the Pi. But when I unplug the microSD, and plug it in any other Pi, when booting up, I get a message saying that eth0 was not found. So there is no network. I've tried it with 3 Pi's so far and Raspbian only detects eth0 on the Pi it was setup on.

Error message:

Cannot find device "eth0"
Bind socket to interface: No such device
Failed to bring up eth0.

Help?

**Comment by goranche** [comment] 2015-10-28 05:20
might this be a duplicate of #103 ?

**Comment by aristosv** [comment] 2015-10-28 05:29
Thanks for your reply. I've read that post.
To be clear, if I add these two lines in post-install.txt will the problem be resolved?

sed -i -e 's/KERNEL\!=\"eth\*|/KERNEL\!=\"/' /lib/udev/rules.d/75-persistent-net-generator.rules
dpkg-divert --add --local /lib/udev/rules.d/75-persistent-net-generator.rules

Thanks

**Comment by goranche** [comment] 2015-10-28 05:42
just to be sure it's the same issue, remove the file ```rm -f /etc/udev/rules.d/70-persistent-net.rules``` before moving the SD card to a different raspberry (it should be recreated there, so it will not work on the first one anymore)...

if that works, you might try adding ```net.ifnames=0``` to cmdline.txt (and deleting the persistent rules file)...

and you can use [this](https://github.com/debian-pi/raspbian-ua-netinst/issues/103#issuecomment-54517762) for future installs... but do keep in mind that it's a workaround, it changes files (well, one file) that come with system packages

**Comment by aristosv** [comment] 2015-10-28 06:48
Your suggestion worked. 
How can I make sure that the system file that changed, never goes back to its original state?
I'm worried because I'll be using this image on 45 raspberry pi's, and I don't want them to suddenly lose their network connectivity, after an X amount of time.

**Comment by goranche** [comment] 2015-10-28 06:50
adding ```net.ifnames=0``` to cmdline.txt should do the trick (if I understand correctly, that is)

**Comment by diederikdehaas** [comment] 2015-10-28 11:55
> How can I make sure that the system file that changed, never goes back to its original state?

By using `dpkg-divert` as described [here](https://github.com/debian-pi/raspbian-ua-netinst/issues/103#issuecomment-58824684)

**Comment by goranche** [comment] 2015-10-28 11:59
> By using dpkg-divert

I wouldn't really do that if at all possible, as it requires changing a "system" library script, and then marking it as "non-upgrade-able" (yeah, not a word, I know)... there is potential for much pain later in time

**Comment by goranche** [comment] 2015-11-01 09:37
@aristosv are you ok now, can we close this issue? (considering #103 is still open, and will probably remain so)

**Comment by aristosv** [comment] 2015-11-01 12:00
yes, thank you

**Closed** 2015-11-01 12:00 UTC
