### ISSUE TITLE
GPIO Hardware not working "out of the box"

### ISSUE THREAD

**Issue by goranche** [debian-pi/raspbian-ua-netinst#111] opened 2014-09-23 09:03 UTC
I've been trying to connect an LCD (from the Nokia 5110) to the raspberry, but found that a raspbian-ua-netinst based install doesn't come with the required support to do so.

the two main things (but might not be limited to these) missing are SPI support and GPIO libs.

will take a look at the official raspbian and occidentalis (adafruits version of raspbian) too see what additional packages / software might be needed for this

**Comment by pierre-haessig** [comment] 2015-01-09 12:54
@diederikdehaas sorry for the lack of feedback. My raspberry and my work on it have been in stand by for many weeks now. It may be more weeks before I start it again, sorry.

**Comment by diederikdehaas** [comment] 2015-01-09 14:22
Thanks for your message @pierre-haessig :+1: 
I've submitted the kernel changes to plugwash and he said he'll change the kernel config based on that. Whether that will cause any issues ... we'll see :wink:

**Comment by goranche** [comment] 2015-01-10 09:15
I hope I'll find some time to get back on this soon...
I've switched to the beaglebone black for the project I was working on, the PRUs proved to be worth their weight in gold for my needs :)
but still, I'd like to get it running on RPi (B+) as well :smile:

**Comment by diederikdehaas** [comment] 2015-01-12 00:32
plugwash has created and uploaded kernel version 3.12.9-1+rpi3 which enables various things wrt GPIO and [requested those changes to be tested](https://bugs.launchpad.net/raspbian/+bug/1403865).
So if any of you could test things and report back (preferably (also) on the raspbian bug), that would be great.

**Comment by goranche** [comment] 2015-01-12 06:06
darn... let's see if I have any unused SPI stuff lying around :smile:

**Comment by solusipse** [comment] 2015-07-31 15:10
In current version, to enable SPI, just remove `device_tree=` from `/boot/config.txt` and add this line to the bottom of it: `dtparam=spi=on`, then reboot. Device tree will even load necessary modules on start. Unfortunately, I was unable to configure it on devices that were updated with `rpi-update` so I wouldn't recommend doing that. Tested on RPi A, B and 2.

**Comment by diederikdehaas** [comment] 2016-02-21 23:43
Any reason to keep this issue still open?

Various things have been added to the kernel so it should be supported. Device Tree still not working properly in all cases is not something we can fix.
Furthermore the issue is quite general (and could thus stay open forever) and to me it would make more sense that a new issue would be opened when a specific hardware device should be supported.

**Comment by Mausy5043** [comment] 2016-10-13 16:27
Closing this issue. Please feel free to re-open if you feel the issue still needs attention.

**Closed by Mausy5043** 2016-10-13 16:27 UTC
